// Data pools for the DEMO_MODE catalog generator (scripts/seed-demo.mjs).
// Temporary demo-only content — not used by the application at runtime.
// Every image URL here is copied from the prototype's vetted stock-photo set (src/data.ts).

const IMG = (id, slug = 'pexels-photo') => `https://images.pexels.com/photos/${id}/${slug}-${id}.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop`;

export const AVATARS = [
  'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/6975099/pexels-photo-6975099.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
  'https://images.pexels.com/photos/1462630/pexels-photo-1462630.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
];

export const PERSON_NAMES = [
  'Alex Rivera', 'Sarah Chen', 'Marcus Johnson', 'Priya Patel', 'Jordan Blake', 'Elena Sokolov',
  'Daniel Okafor', 'Mia Nguyen', 'Carlos Mendes', 'Hannah Goldberg', 'Omar Haddad', 'Grace Kim',
  'Tyler Brooks', 'Aisha Rahman', 'Lucas Moreau', 'Nina Kowalski', 'Devin Wright', 'Sofia Alvarez',
  'Ethan Caldwell', 'Leila Farouk', 'Ryan O\u2019Connell', 'Yuki Tanaka', 'Brandon Ellis', 'Camila Rojas',
  'Nathan Frost', 'Zoe Whitfield', 'Isaac Bergman', 'Tara Singh', 'Miles Donovan', 'Ava Lindqvist',
  'Samuel Adeyemi', 'Rachel Stern', 'Victor Pham', 'Chloe Bennett', 'Amir Kaz', 'Bianca Ferraro',
];

// Real Dallas–Fort Worth metroplex coordinates, so map/distance filters behave believably.
export const CITIES = [
  { label: 'Dallas, TX', lat: 32.7767, lng: -96.797 },
  { label: 'Irving, TX', lat: 32.814, lng: -96.9489 },
  { label: 'Las Colinas, TX', lat: 32.8752, lng: -96.9469 },
  { label: 'Plano, TX', lat: 33.0198, lng: -96.6989 },
  { label: 'Frisco, TX', lat: 33.1507, lng: -96.8236 },
  { label: 'Arlington, TX', lat: 32.7357, lng: -97.1081 },
  { label: 'Fort Worth, TX', lat: 32.7555, lng: -97.3308 },
  { label: 'Richardson, TX', lat: 32.9483, lng: -96.7299 },
  { label: 'Garland, TX', lat: 32.9126, lng: -96.6389 },
  { label: 'Grapevine, TX', lat: 32.9343, lng: -97.0781 },
  { label: 'Coppell, TX', lat: 32.9546, lng: -96.99 },
  { label: 'McKinney, TX', lat: 33.1972, lng: -96.6398 },
  { label: 'Carrollton, TX', lat: 32.9537, lng: -96.8903 },
  { label: 'Lewisville, TX', lat: 33.0462, lng: -96.994 },
  { label: 'Denton, TX', lat: 33.2148, lng: -97.1331 },
  { label: 'Mesquite, TX', lat: 32.7668, lng: -96.5992 },
  { label: 'Allen, TX', lat: 33.1032, lng: -96.6706 },
  { label: 'Flower Mound, TX', lat: 33.0146, lng: -97.097 },
  { label: 'Rowlett, TX', lat: 32.9029, lng: -96.5638 },
  { label: 'Euless, TX', lat: 32.837, lng: -97.0819 },
  { label: 'Addison, TX', lat: 32.9618, lng: -96.8292 },
  { label: 'Cedar Hill, TX', lat: 32.5885, lng: -96.9561 },
  { label: 'Mansfield, TX', lat: 32.5632, lng: -97.1417 },
  { label: 'Rockwall, TX', lat: 32.931, lng: -96.4597 },
];

const CAMERA_IMAGES = [IMG(19969452), IMG(19969445), IMG(19969447), IMG(14396385)];
const AV_IMAGES = [IMG(5515482), IMG(6552592), IMG(7886852)];
const VR_IMAGES = [IMG(36812934), IMG(7864434), IMG(7561900)];
const TOOL_IMAGES = [IMG(30413428), IMG(30413424), IMG(6790821)];
const CAMP_IMAGES = [IMG(2526025), IMG(30041430), IMG(10513799)];
const PARTY_IMAGES = [IMG(35985211), IMG(9644360), 'https://images.pexels.com/photos/50675/banquet-wedding-society-deco-50675.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop'];
const DJ_IMAGES = [IMG(1481316), IMG(34307990), IMG(6942388)];
const BIKE_IMAGES = [IMG(36450314), IMG(16998814), IMG(11885686)];
const GARDEN_IMAGES = [IMG(37554739), IMG(4162016), IMG(5163429)];
const KITCHEN_IMAGES = [IMG(6996340), IMG(6996347), IMG(6996344)];
const BABY_IMAGES = [IMG(5997705), IMG(15501373), IMG(22491728)];
const MUSIC_IMAGES = [IMG(35486274), IMG(8197270)];

const item = (name, price, deposit, description, images) => ({ name, price, deposit, description, images });

// Per-category item pools. Each entry seeds a family of listings; the generator adds a variant
// suffix, jitters price/deposit, and assigns a city, so combinations stay unique and diverse.
export const CATEGORY_ITEMS = {
  'Electronics': [
    item('Sony A7 IV Mirrorless Camera', 85, 500, 'Full-frame 33MP mirrorless body with 4K60p video and a 24\u201370mm f/2.8 zoom.', CAMERA_IMAGES),
    item('Canon EOS R6 Body + 50mm Lens', 78, 450, 'Fast, low-light-friendly full-frame body with a sharp 50mm f/1.8 prime.', CAMERA_IMAGES),
    item('Nikon Z6 II Kit', 70, 420, 'Weather-sealed hybrid body, dual card slots, two batteries and a charger included.', CAMERA_IMAGES),
    item('GoPro HERO12 Action Bundle', 28, 160, 'Waterproof action camera with chest mount, head strap, and three batteries.', CAMERA_IMAGES),
    item('DJI Mini 4 Pro Drone', 65, 400, 'Sub-250g drone with obstacle sensing, 4K HDR video, and two spare batteries.', CAMERA_IMAGES),
    item('4K Ultra Short Throw Projector', 60, 400, 'Bright 4K short-throw projector \u2014 perfect for movie nights and presentations.', AV_IMAGES),
    item('Portable 1080p Projector + Screen', 32, 180, 'Compact projector with a 100" pull-up screen and HDMI/USB-C inputs.', AV_IMAGES),
    item('Meta Quest 3 VR Headset (128GB)', 30, 150, 'Mixed-reality headset with controllers, silicone face cover, and popular titles installed.', VR_IMAGES),
    item('PlayStation 5 + Two Controllers', 35, 250, 'Disc-edition console with two DualSense controllers and three games.', VR_IMAGES),
    item('Nintendo Switch OLED Party Pack', 22, 140, 'OLED Switch with four controllers and party games for the whole group.', VR_IMAGES),
    item('MacBook Pro 16" M3 Max', 90, 900, 'Editing-ready laptop with 36GB unified memory and a 1TB drive. Charger included.', AV_IMAGES),
    item('iPad Pro 12.9" + Apple Pencil', 34, 300, 'Large-format tablet with Apple Pencil and a Magic Keyboard folio.', AV_IMAGES),
    item('Rode Wireless PRO Mic Kit', 26, 180, 'Dual-channel wireless lav kit with 32-bit float recording and windshields.', CAMERA_IMAGES),
    item('Studio Lighting Kit (3-Point)', 40, 220, 'Three-point LED lighting kit with softboxes, stands, and gels.', CAMERA_IMAGES),
    item('Blackmagic Pocket Cinema 6K', 95, 700, 'Cinema camera with EF mount, V-mount battery plate, and CFast media.', CAMERA_IMAGES),
    item('DJI RS 4 Gimbal Stabilizer', 38, 260, 'Three-axis gimbal rated for mirrorless bodies up to 3kg. Case included.', CAMERA_IMAGES),
    item('LG 55" 4K OLED TV on Stand', 55, 400, 'Rolling-stand 55" OLED for pop-ups, demos, and living-room upgrades.', AV_IMAGES),
    item('Sonos Move 2 Speaker Pair', 24, 150, 'Two battery-powered smart speakers that pair for true stereo outdoors.', AV_IMAGES),
    item('Starlink Mini Internet Kit', 45, 350, 'Portable satellite internet kit for remote shoots and off-grid weekends.', AV_IMAGES),
    item('Anker 2kWh Portable Power Station', 48, 380, 'Silent LiFePO4 battery station with AC, USB-C PD, and 12V outputs.', AV_IMAGES),
  ],
  'Tools & Equipment': [
    item('DeWalt 20V Cordless Drill Kit', 25, 100, 'Professional-grade cordless drill with two 20V batteries, charger, and a full bit set.', TOOL_IMAGES),
    item('Milwaukee M18 Impact Driver Set', 28, 120, 'High-torque impact driver with two batteries, rapid charger, and impact bits.', TOOL_IMAGES),
    item('Makita 10" Table Saw', 45, 250, 'Portable jobsite table saw with rolling stand, riving knife, and a fresh blade.', TOOL_IMAGES),
    item('Bosch 12" Sliding Miter Saw', 42, 240, 'Dual-bevel sliding miter saw with stand and laser guide.', TOOL_IMAGES),
    item('Pressure Washer 3200 PSI', 38, 200, 'Gas pressure washer with four quick-connect nozzles and a surface cleaner.', TOOL_IMAGES),
    item('Wet Tile Saw (7")', 35, 180, 'Wet-cut tile saw with sliding table \u2014 ideal for bathroom and backsplash jobs.', TOOL_IMAGES),
    item('Drywall Lift + Taping Set', 30, 150, 'Drywall panel lift plus taping knives, mud pan, and sanding pole.', TOOL_IMAGES),
    item('Rotary Hammer Drill (SDS-Max)', 48, 280, 'Heavy concrete drilling and chipping hammer with assorted bits and chisels.', TOOL_IMAGES),
    item('Floor Sander + Edger', 75, 400, 'Drum floor sander with edger and a starter pack of abrasive discs.', TOOL_IMAGES),
    item('Scaffold Tower (12 ft)', 55, 300, 'Rolling scaffold tower with guardrails, outriggers, and planks.', TOOL_IMAGES),
    item('Generator 7500W Dual Fuel', 70, 450, 'Dual-fuel generator with electric start and a 50A transfer-ready outlet.', TOOL_IMAGES),
    item('Welding Setup (MIG 180A)', 60, 400, 'MIG welder with helmet, gloves, wire spool, and a regulator.', TOOL_IMAGES),
    item('Air Compressor + Nail Gun Kit', 40, 220, '6-gallon compressor with framing and finish nailers, hose, and fittings.', TOOL_IMAGES),
    item('Concrete Mixer (5 cu ft)', 52, 300, 'Towable electric drum mixer for footings, slabs, and mortar work.', TOOL_IMAGES),
    item('Laser Level + Tripod Kit', 22, 140, 'Self-leveling cross-line laser with tripod, receiver, and target card.', TOOL_IMAGES),
    item('Stump Grinder', 110, 600, 'Walk-behind stump grinder with a fresh cutter wheel and safety gear.', TOOL_IMAGES),
    item('Plate Compactor', 58, 350, 'Vibratory plate compactor for paver bases, driveways, and trenches.', TOOL_IMAGES),
    item('Pipe Threading Machine', 65, 420, 'Portable pipe threader with dies, cutter, and reamer for 1/2"\u20132" pipe.', TOOL_IMAGES),
    item('Auto Diagnostic Scanner Kit', 26, 180, 'Bi-directional OBD-II scanner with tablet, adapters, and case.', TOOL_IMAGES),
    item('Engine Hoist + Stand', 44, 260, '2-ton folding engine hoist with load leveler and rotating engine stand.', TOOL_IMAGES),
  ],
  'Outdoor & Camping': [
    item('4-Person Camping Tent + Sleeping Bags', 35, 150, 'Waterproof 4-person dome tent with rain fly, four sleeping bags, and pads.', CAMP_IMAGES),
    item('8-Person Family Cabin Tent', 48, 220, 'Room-divider cabin tent with standing height and a screened porch.', CAMP_IMAGES),
    item('Ultralight Backpacking Kit (2P)', 42, 260, 'Two-person trekking-pole tent, quilts, and a titanium stove system.', CAMP_IMAGES),
    item('Rooftop Tent (Hard Shell)', 85, 500, 'Clamshell rooftop tent with mattress and ladder. Crossbars required.', CAMP_IMAGES),
    item('Tandem Kayak + Paddles', 45, 250, 'Sit-on-top tandem kayak with two paddles, PFDs, and roof straps.', CAMP_IMAGES),
    item('Inflatable Paddleboard Pair', 38, 200, 'Two iSUPs with pump, paddles, leashes, and travel backpacks.', CAMP_IMAGES),
    item('Yeti Tundra 65 Cooler', 18, 120, 'Roto-molded cooler that holds ice for days. Includes basket and dry goods tray.', CAMP_IMAGES),
    item('Camp Kitchen + Stove Set', 24, 130, 'Two-burner propane stove, roll table, cookware, and a wash bin.', CAMP_IMAGES),
    item('Portable Fire Pit + Grill Grate', 16, 90, 'Smokeless fire pit with a swing-away grill grate and carry bag.', CAMP_IMAGES),
    item('Fishing Gear Bundle (2 Rods)', 28, 160, 'Two spinning rods, tackle box, landing net, and a cooler.', CAMP_IMAGES),
    item('Hiking Pack + Trekking Poles', 20, 110, '65L internal-frame pack, rain cover, and carbon trekking poles.', CAMP_IMAGES),
    item('Overlanding Awning + Chairs', 34, 190, 'Vehicle-mount 270\u00b0 awning with four camp chairs and a table.', CAMP_IMAGES),
    item('Climbing Rack + Ropes', 46, 320, 'Sport rack with quickdraws, 70m rope, harnesses, and belay devices.', CAMP_IMAGES),
    item('Snowboard + Boots (Size 10)', 40, 250, 'All-mountain board with bindings, boots, and a padded travel bag.', CAMP_IMAGES),
    item('Camping Generator + Solar Panel', 52, 340, 'Quiet inverter generator paired with a 200W folding solar panel.', CAMP_IMAGES),
    item('Hammock Camping Set (2P)', 15, 80, 'Two hammocks with tree straps, bug nets, tarps, and underquilts.', CAMP_IMAGES),
    item('Metal Detector + Sand Scoop', 19, 110, 'Waterproof coil metal detector with headphones and a sand scoop.', CAMP_IMAGES),
    item('Telescope (8" Dobsonian)', 36, 280, 'Large-aperture Dobsonian with eyepieces, filters, and a red-light torch.', CAMP_IMAGES),
    item('Beach Day Bundle', 22, 120, 'Two canopies, four chairs, a cooler, and a wagon to haul it all.', CAMP_IMAGES),
    item('Off-Road Recovery Kit', 30, 200, 'Traction boards, kinetic rope, soft shackles, and a folding shovel.', CAMP_IMAGES),
  ],
  'Party & Events': [
    item('Round Banquet Tables (10) + Chairs (80)', 120, 300, 'Complete party setup: ten 60" round banquet tables and 80 padded chairs.', PARTY_IMAGES),
    item('Pioneer DDJ-1000 DJ Controller', 75, 350, 'Four-channel DJ controller with full-size jog wheels, Rekordbox ready.', DJ_IMAGES),
    item('Powered PA Speaker Pair + Stands', 65, 320, 'Two 15" powered speakers, tripod stands, cables, and a small mixer.', DJ_IMAGES),
    item('Wireless Microphone Set (4)', 30, 180, 'Four-channel wireless handheld mic system with receiver and cables.', DJ_IMAGES),
    item('20x20 Event Tent', 140, 500, 'White frame tent with sidewalls, stakes, and setup instructions.', PARTY_IMAGES),
    item('Bounce House + Blower', 95, 350, 'Commercial-grade bounce house with blower, stakes, and a ground tarp.', PARTY_IMAGES),
    item('Photo Booth with Props', 110, 400, 'Touchscreen photo booth with printer, backdrop, ring light, and prop box.', PARTY_IMAGES),
    item('Uplighting Package (12 Fixtures)', 70, 300, 'Twelve battery-powered RGB uplights with a wireless remote.', DJ_IMAGES),
    item('Dance Floor (16x16)', 160, 600, 'Interlocking portable dance floor with edge trim and a dolly.', PARTY_IMAGES),
    item('Chocolate Fountain + Chafers', 45, 200, 'Three-tier chocolate fountain plus six chafing dishes with fuel.', PARTY_IMAGES),
    item('Margarita & Slush Machine', 85, 300, 'Double-hopper frozen drink machine, cleaned and ready to serve.', PARTY_IMAGES),
    item('Wedding Arch + Drapery', 55, 250, 'Adjustable metal arch with sheer drapery and floral clamps.', PARTY_IMAGES),
    item('Outdoor Movie Night Kit', 68, 320, '16-foot inflatable screen, projector, blower, and outdoor sound.', PARTY_IMAGES),
    item('Karaoke System + Tablets', 40, 200, 'Karaoke machine with two mics, tablets, and a huge licensed song list.', DJ_IMAGES),
    item('Cotton Candy + Popcorn Carts', 60, 250, 'Two vintage-style carts with supplies for roughly 100 servings.', PARTY_IMAGES),
    item('Stage Risers (4 Sections)', 90, 400, 'Four 4x8 stage decks with adjustable legs, skirting, and steps.', PARTY_IMAGES),
    item('Cocktail Tables (12) + Linens', 65, 220, 'Twelve highboy cocktail tables with black and white spandex linens.', PARTY_IMAGES),
    item('Patio Heater Set (4)', 50, 220, 'Four propane patio heaters with covers. Tanks not included.', PARTY_IMAGES),
    item('Kids Party Package', 75, 250, 'Tables, chairs, games, piñata stand, and decorations for 20 kids.', PARTY_IMAGES),
    item('Truss & Lighting Rig', 130, 550, 'Portable truss system with moving heads, hazer, and a DMX controller.', DJ_IMAGES),
  ],
  'Sports & Fitness': [
    item('Trek Full Suspension Mountain Bike', 45, 600, 'Trek Fuel EX 8 trail bike, size L. Helmet and heavy-duty lock included.', BIKE_IMAGES),
    item('Road Bike (Carbon, 54cm)', 42, 550, 'Carbon endurance road bike with clipless pedals and a spare tube kit.', BIKE_IMAGES),
    item('Gravel Bike + Bikepacking Bags', 44, 520, 'Gravel bike with frame, seat, and handlebar bags for overnight rides.', BIKE_IMAGES),
    item('Peloton-Style Smart Bike', 38, 400, 'Smart indoor trainer bike with tablet mount and cycling shoes.', BIKE_IMAGES),
    item('Adjustable Dumbbell Set (5\u201352 lb)', 26, 220, 'Pair of adjustable dumbbells with a stand \u2014 a whole rack in one footprint.', BIKE_IMAGES),
    item('Home Squat Rack + Barbell', 48, 350, 'Squat rack, Olympic barbell, and 300 lb of bumper plates.', BIKE_IMAGES),
    item('Rowing Machine (Air)', 32, 250, 'Air rower with performance monitor, folds for storage.', BIKE_IMAGES),
    item('Golf Clubs (Full Set, RH)', 35, 300, 'Full right-handed set with stand bag, rangefinder, and two dozen balls.', BIKE_IMAGES),
    item('Tennis Ball Machine', 40, 320, 'Programmable ball machine with remote, 150 balls, and a charger.', BIKE_IMAGES),
    item('Kayak Roof Rack System', 18, 140, 'J-cradle roof rack with straps and bow/stern tie-downs.', BIKE_IMAGES),
    item('Electric Scooter (Long Range)', 30, 300, 'Dual-motor scooter with a 40-mile range, helmet, and charger.', BIKE_IMAGES),
    item('Ski Set + Boots (Size 11)', 44, 350, 'All-mountain skis, poles, boots, and a padded travel bag.', BIKE_IMAGES),
    item('Volleyball & Cornhole Set', 16, 90, 'Portable net system, volleyballs, and two regulation cornhole boards.', BIKE_IMAGES),
    item('Boxing Bag + Gloves', 20, 130, 'Freestanding heavy bag with two pairs of gloves and wraps.', BIKE_IMAGES),
    item('Kids Bike Fleet (4 Sizes)', 28, 180, 'Four kids bikes from 16" to 24" with helmets \u2014 perfect for visiting families.', BIKE_IMAGES),
    item('Inflatable Kayak (2P)', 30, 200, 'Drop-stitch inflatable kayak with pump, paddles, and repair kit.', BIKE_IMAGES),
    item('Surfboard + Wetsuit', 34, 240, '8-foot funboard with leash, wax, and a 3/2 wetsuit.', BIKE_IMAGES),
    item('Disc Golf Pro Bag', 14, 80, 'Tournament bag with 18 discs across putters, midranges, and drivers.', BIKE_IMAGES),
    item('Pickleball Court Kit', 24, 140, 'Portable net, four paddles, balls, and court-marking tape.', BIKE_IMAGES),
    item('Indoor Climbing Training Board', 22, 160, 'Hangboard, portable rings, resistance bands, and a crash pad.', BIKE_IMAGES),
  ],
  'Vehicles': [
    item('RadWagon Electric Cargo E-Bike', 40, 300, 'Cargo e-bike with pedal assist and a 45-mile range. Helmet and lock included.', BIKE_IMAGES),
    item('Electric Commuter Bike', 32, 250, 'Step-through e-bike with fenders, rear rack, and integrated lights.', BIKE_IMAGES),
    item('Fat Tire E-Bike (All Terrain)', 45, 320, 'Fat-tire e-bike for sand and trails, with a spare battery.', BIKE_IMAGES),
    item('Utility Trailer (5x8)', 38, 280, 'Open utility trailer with ramp gate and 2" ball coupler.', TOOL_IMAGES),
    item('Enclosed Cargo Trailer (6x12)', 68, 450, 'Lockable enclosed trailer with D-rings and interior lighting.', TOOL_IMAGES),
    item('Motorcycle Carrier Hitch Rack', 25, 180, 'Hitch-mounted motorcycle carrier with loading ramp and straps.', TOOL_IMAGES),
    item('Car Dolly', 55, 400, 'Tow dolly with straps and lighting harness for front-wheel-drive cars.', TOOL_IMAGES),
    item('Teardrop Camper Trailer', 130, 800, 'Sleeps two, with a galley kitchen, solar, and a fridge.', CAMP_IMAGES),
    item('Pop-Up Camper', 110, 700, 'Sleeps six, with a dinette, fridge, and roll-out awning.', CAMP_IMAGES),
    item('Electric Moped (Street Legal)', 48, 400, 'Licensed electric moped, 45 mph top speed, with two helmets.', BIKE_IMAGES),
    item('Golf Cart (4-Seat, Electric)', 85, 500, 'Street-ready electric golf cart with lights, seat belts, and a charger.', BIKE_IMAGES),
    item('Jet Ski Trailer', 42, 300, 'Single-watercraft trailer with a winch and bunk carpeting.', TOOL_IMAGES),
    item('Bike Rack (4-Bike Hitch)', 15, 120, '4-bike platform hitch rack with tilt-away and a locking hitch pin.', BIKE_IMAGES),
    item('Kids Ride-On Fleet', 22, 150, 'Two electric ride-ons and two balance bikes with helmets.', BIKE_IMAGES),
    item('ATV Ramps + Tie-Downs', 18, 120, 'Pair of 7-foot arched aluminum ramps with ratchet tie-downs.', TOOL_IMAGES),
    item('Onewheel GT', 50, 450, 'Onewheel GT with charger, fender, and full protective gear.', BIKE_IMAGES),
    item('Electric Skateboard (Boosted-Class)', 35, 280, 'Belt-drive electric longboard with remote, charger, and pads.', BIKE_IMAGES),
    item('Dump Trailer (6x10)', 145, 900, 'Hydraulic dump trailer for landscaping and demo hauls.', TOOL_IMAGES),
    item('Van Roof Box + Crossbars', 20, 140, 'Aerodynamic 18 cu ft cargo box with crossbars and keys.', TOOL_IMAGES),
    item('Adaptive Handcycle', 40, 300, 'Adaptive handcycle with adjustable fit and a transport bag.', BIKE_IMAGES),
  ],
  'Home & Garden': [
    item('Self-Propelled Lawn Mower', 30, 150, 'Honda self-propelled mower with bagging and mulching modes. 21" deck.', GARDEN_IMAGES),
    item('Zero-Turn Riding Mower', 95, 600, '42" zero-turn mower \u2014 makes short work of large lots.', GARDEN_IMAGES),
    item('Tiller / Cultivator', 38, 220, 'Rear-tine tiller for breaking new garden beds and mixing compost.', GARDEN_IMAGES),
    item('Log Splitter (25 Ton)', 72, 450, 'Towable 25-ton gas log splitter with horizontal and vertical modes.', GARDEN_IMAGES),
    item('Chainsaw + Safety Kit', 28, 180, '18" gas chainsaw with chaps, helmet, gloves, and bar oil.', GARDEN_IMAGES),
    item('Leaf Blower / Vacuum (Backpack)', 24, 140, 'Backpack blower with a vacuum-and-mulch attachment.', GARDEN_IMAGES),
    item('Aerator + Overseeder', 60, 350, 'Core aerator and overseeder combo for a lawn reset weekend.', GARDEN_IMAGES),
    item('Hedge Trimmer + Pole Saw', 26, 160, 'Battery hedge trimmer with an extending pole saw and two batteries.', GARDEN_IMAGES),
    item('KitchenAid Stand Mixer + Attachments', 20, 150, 'Artisan 5-qt stand mixer with paddle, whisk, dough hook, and pasta roller.', KITCHEN_IMAGES),
    item('Commercial Espresso Machine', 55, 400, 'Dual-boiler espresso machine with grinder, tamper, and milk pitchers.', KITCHEN_IMAGES),
    item('Outdoor Pizza Oven + Peels', 40, 220, 'Gas-fired pizza oven that hits 900\u00b0F, with peels and an IR thermometer.', KITCHEN_IMAGES),
    item('Smoker / Offset BBQ', 58, 300, 'Offset smoker with a temperature controller and two probes.', KITCHEN_IMAGES),
    item('Carpet Cleaner (Deep Clean)', 32, 180, 'Hot-water extraction carpet cleaner with upholstery and stair tools.', GARDEN_IMAGES),
    item('Steam Cleaner + Floor Set', 22, 130, 'Multi-surface steam cleaner with tile, grout, and garment attachments.', GARDEN_IMAGES),
    item('Dehumidifier (70 Pint)', 26, 160, 'High-capacity dehumidifier with a pump and drain hose.', GARDEN_IMAGES),
    item('Air Mattress + Guest Bedding Set', 15, 80, 'Two queen air beds with pumps, sheets, pillows, and blankets.', KITCHEN_IMAGES),
    item('Wallpaper Steamer + Paint Sprayer', 30, 170, 'Wallpaper steamer plus an HVLP paint sprayer with tips and masks.', TOOL_IMAGES),
    item('Sewing & Embroidery Machine', 24, 180, 'Computerized sewing and embroidery machine with hoops and thread.', KITCHEN_IMAGES),
    item('Greenhouse Starter Kit', 28, 160, 'Walk-in greenhouse frame with shelving, heat mats, and grow lights.', GARDEN_IMAGES),
    item('Hot Tub (Inflatable, 6-Person)', 88, 400, 'Six-person inflatable spa with heater, pump, cover, and chemical kit.', GARDEN_IMAGES),
  ],
  'Other': [
    item('BOB Revolution Stroller + Car Seat', 15, 100, 'Jogging stroller with infant car seat adapter. Cleaned and safety-checked.', BABY_IMAGES),
    item('Travel Crib + High Chair', 14, 90, 'Pack-and-play travel crib with a clip-on high chair and a monitor.', BABY_IMAGES),
    item('Double Stroller (All Terrain)', 20, 130, 'Side-by-side double stroller with rain cover and a sun canopy.', BABY_IMAGES),
    item('Baby Gear Travel Bundle', 24, 150, 'Car seat, stroller, crib, monitor, and gates \u2014 everything for visiting family.', BABY_IMAGES),
    item('Fender Stratocaster + Boss Katana Amp', 40, 400, 'American Professional Strat with a Katana 100W amp, cable, strap, and gig bag.', MUSIC_IMAGES),
    item('Electronic Drum Kit', 45, 350, 'Mesh-head electronic kit with throne, pedals, and headphones.', MUSIC_IMAGES),
    item('Upright Digital Piano (88 Key)', 38, 300, 'Weighted 88-key digital piano with a bench and sustain pedal.', MUSIC_IMAGES),
    item('Podcast Studio Kit', 42, 280, 'Four mics, a Rodecaster mixer, boom arms, headphones, and cables.', MUSIC_IMAGES),
    item('Bass Guitar + Combo Amp', 32, 260, 'Precision-style bass with a 100W combo amp, cable, and stand.', MUSIC_IMAGES),
    item('Violin (4/4) + Case', 18, 200, 'Full-size violin with bow, rosin, shoulder rest, and a hard case.', MUSIC_IMAGES),
    item('Sewing Mannequin + Garment Rack', 12, 70, 'Adjustable dress form with a rolling garment rack and steamer.', KITCHEN_IMAGES),
    item('Costume & Cosplay Trunk', 26, 150, 'Themed costume trunk with accessories and props in mixed sizes.', PARTY_IMAGES),
    item('Board Game Night Library', 10, 60, 'Twenty modern board games with rules sheets and card sleeves.', PARTY_IMAGES),
    item('Telescope for Kids + Star Charts', 14, 90, 'Beginner-friendly refractor with star charts and a red torch.', CAMP_IMAGES),
    item('Mobility Scooter', 40, 300, 'Four-wheel mobility scooter with a charger and a captain seat.', BIKE_IMAGES),
    item('Wheelchair + Ramp Set', 28, 200, 'Lightweight transport wheelchair with a folding threshold ramp.', BIKE_IMAGES),
    item('3D Printer (Bambu-Class)', 35, 280, 'Enclosed CoreXY 3D printer with two spools of filament.', AV_IMAGES),
    item('Laser Engraver (Diode)', 44, 320, '10W diode laser engraver with safety glasses and material samples.', AV_IMAGES),
    item('Vinyl Cutter + Heat Press', 38, 260, 'Craft cutter with a 15x15 heat press, vinyl, and transfer sheets.', KITCHEN_IMAGES),
    item('Film Scanner + Slide Digitizer', 16, 120, 'Batch film and slide scanner with software and cleaning supplies.', CAMERA_IMAGES),
  ],
};

export const VARIANTS = [
  '', 'Pro Kit', 'Weekend Bundle', '2024 Model', 'Compact Edition', 'Heavy Duty', 'Starter Set',
  'Deluxe Package', 'Twin Pack', 'Traveler Edition', 'Complete Setup', 'Premium Trim',
];

export const CONDITION_NOTES = [
  'Well maintained and cleaned before every rental.',
  'Lightly used, stored indoors, and inspected before pickup.',
  'Bought new this year \u2014 still under manufacturer warranty.',
  'Serviced regularly; consumables replaced as needed.',
  'A few cosmetic marks, but everything works perfectly.',
  'Pickup available evenings and weekends; local delivery possible.',
  'Quick handoff with a short walkthrough so you know how it all works.',
];

export const REVIEW_TEXTS = [
  'Exactly as described and in great shape. Easy pickup, friendly owner.',
  'Worked flawlessly for the whole rental. Would rent again.',
  'Clean, well-maintained, and ready to go. Smooth handoff.',
  'Great value and the owner was super responsive. Highly recommend.',
  'Everything included as promised. Return was quick and simple.',
  'Saved me from buying one for a single weekend project. Perfect.',
  'Owner walked me through the setup \u2014 really helpful for a first-timer.',
  'Communication was fast and pickup was right on time.',
  'Good gear, fair price, zero hassle. Five stars.',
  'Minor wear but performed exactly how I needed it to.',
];

export const MESSAGE_THREADS = [
  ['Hi! Is this still available for the dates I picked?', 'Yes, it is \u2014 I just confirmed the calendar.', 'Great, sending the request now.', 'Perfect, I\u2019ll approve it as soon as it comes through.'],
  ['Do you offer delivery within about 10 miles?', 'I do, for a small fee. Where are you located?', 'Near Las Colinas. That works for me.', 'Easy \u2014 I\u2019ll drop it off the morning your rental starts.'],
  ['Any chance I could pick it up a bit early?', 'Sure, anytime after 4pm works on my end.', 'Awesome, see you then.'],
  ['Is everything included, or do I need to bring anything?', 'Everything is included except fuel. I\u2019ll send a checklist.', 'Perfect, thanks for the quick reply!'],
  ['Just returned it \u2014 thanks again, it worked great!', 'Glad to hear it! Everything looked perfect on my end.', 'I\u2019ll leave you a review now.'],
  ['Could I extend by one extra day?', 'Let me check the calendar\u2026 yes, that day is open.', 'Great, I\u2019ll update the booking.'],
];
