export type ThemeId =
  | 'coral'
  | 'forest'
  | 'ocean'
  | 'slate'
  | 'sunset'
  | 'mono'
  | 'sand'
  | 'berry'
  | 'midnight'
  | 'aurora';

export interface Theme {
  id: ThemeId;
  name: string;
  dark: boolean;
  /** short tagline shown in the switcher */
  tagline: string;
  /** CSS variable values applied to :root */
  vars: Record<string, string>;
}

const baseVars = {
  '--radius': '0.75rem',
  '--radius-lg': '1rem',
  '--radius-xl': '1.25rem',
  '--radius-sm': '0.5rem',
  '--shadow-card': '0 1px 3px rgba(0,0,0,0.06), 0 8px 24px rgba(0,0,0,0.06)',
  '--shadow-hover': '0 4px 12px rgba(0,0,0,0.08), 0 16px 40px rgba(0,0,0,0.10)',
  '--font-sans': "'Inter', system-ui, -apple-system, sans-serif",
  '--font-display': "'Inter', system-ui, sans-serif",
};

function makeTheme(
  id: ThemeId,
  name: string,
  tagline: string,
  dark: boolean,
  colors: Record<string, string>,
  fonts?: Partial<Record<'--font-sans' | '--font-display', string>>,
): Theme {
  return {
    id,
    name,
    tagline,
    dark,
    vars: { ...baseVars, ...colors, ...(fonts ?? {}) },
  };
}

export const themes: Theme[] = [
  makeTheme(
    'coral',
    'Coral Market',
    'Warm white + coral, Airbnb-inspired',
    false,
    {
      '--bg': '#FAFAF8',
      '--bg-subtle': '#F4F2EE',
      '--bg-card': '#FFFFFF',
      '--text': '#171717',
      '--text-secondary': '#6B6B6B',
      '--text-muted': '#9A9A96',
      '--border': '#E7E5E2',
      '--border-strong': '#D4D1CC',
      '--accent': '#E0533D',
      '--accent-hover': '#C8442F',
      '--accent-soft': '#FCEDEA',
      '--accent-text': '#FFFFFF',
      '--success': '#3F8F5C',
      '--success-soft': '#E8F5EC',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#D14430',
      '--error-soft': '#FCE9E6',
      '--star': '#E8A53A',
    },
  ),
  makeTheme(
    'forest',
    'Forest',
    'Cream + deep green, earthy marketplace',
    false,
    {
      '--bg': '#F6F5F0',
      '--bg-subtle': '#EDEAE2',
      '--bg-card': '#FFFFFF',
      '--text': '#1A1F1B',
      '--text-secondary': '#5C6B5F',
      '--text-muted': '#8E9C92',
      '--border': '#E0DCD3',
      '--border-strong': '#CFC9BD',
      '--accent': '#2D6A4F',
      '--accent-hover': '#245540',
      '--accent-soft': '#E2EFE7',
      '--accent-text': '#FFFFFF',
      '--success': '#3F8F5C',
      '--success-soft': '#E8F5EC',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#B14A3A',
      '--error-soft': '#F8E8E4',
      '--star': '#D9A441',
    },
  ),
  makeTheme(
    'ocean',
    'Ocean Green',
    'Cool white + ocean green, clean and crisp',
    false,
    {
      '--bg': '#F7FAF9',
      '--bg-subtle': '#EBF4F1',
      '--bg-card': '#FFFFFF',
      '--text': '#0F2A28',
      '--text-secondary': '#4E7A70',
      '--text-muted': '#8AB3A6',
      '--border': '#DFEDE8',
      '--border-strong': '#C7DED6',
      '--accent': '#0E7C66',
      '--accent-hover': '#0A6553',
      '--accent-soft': '#DDF3EC',
      '--accent-text': '#FFFFFF',
      '--success': '#2E8B57',
      '--success-soft': '#E2F3EA',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#C8453A',
      '--error-soft': '#FBE7E5',
      '--star': '#E0A538',
    },
  ),
  makeTheme(
    'slate',
    'Slate',
    'Gray + indigo accent, dense utility',
    false,
    {
      '--bg': '#F4F5F7',
      '--bg-subtle': '#E9EBEE',
      '--bg-card': '#FFFFFF',
      '--text': '#1B1F23',
      '--text-secondary': '#596069',
      '--text-muted': '#8A929C',
      '--border': '#DFE2E6',
      '--border-strong': '#C7CCD3',
      '--accent': '#3D5AFE',
      '--accent-hover': '#2E49D6',
      '--accent-soft': '#E8EDFE',
      '--accent-text': '#FFFFFF',
      '--success': '#2E8B57',
      '--success-soft': '#E2F3EA',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#D14430',
      '--error-soft': '#FCE9E6',
      '--star': '#E8A53A',
    },
  ),
  makeTheme(
    'sunset',
    'Sunset',
    'Peach + amber, warm and friendly',
    false,
    {
      '--bg': '#FDF8F4',
      '--bg-subtle': '#F7EDE3',
      '--bg-card': '#FFFFFF',
      '--text': '#2A1E16',
      '--text-secondary': '#6E5A4E',
      '--text-muted': '#A18D80',
      '--border': '#EDE0D4',
      '--border-strong': '#DAC9B8',
      '--accent': '#E07A2C',
      '--accent-hover': '#C26820',
      '--accent-soft': '#FBE6D4',
      '--accent-text': '#FFFFFF',
      '--success': '#3F8F5C',
      '--success-soft': '#E8F5EC',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#C8453A',
      '--error-soft': '#FBE7E5',
      '--star': '#E8A53A',
    },
  ),
  makeTheme(
    'mono',
    'Mono',
    'Pure white + black, Apple-minimal',
    false,
    {
      '--bg': '#FFFFFF',
      '--bg-subtle': '#F5F5F5',
      '--bg-card': '#FFFFFF',
      '--text': '#111111',
      '--text-secondary': '#555555',
      '--text-muted': '#999999',
      '--border': '#EAEAEA',
      '--border-strong': '#D4D4D4',
      '--accent': '#111111',
      '--accent-hover': '#333333',
      '--accent-soft': '#F0F0F0',
      '--accent-text': '#FFFFFF',
      '--success': '#2E8B57',
      '--success-soft': '#E2F3EA',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#D14430',
      '--error-soft': '#FCE9E6',
      '--star': '#E8A53A',
    },
    { '--font-display': "'Georgia', 'Times New Roman', serif" },
  ),
  makeTheme(
    'sand',
    'Sand',
    'Beige + terracotta, desert calm',
    false,
    {
      '--bg': '#F5F0E8',
      '--bg-subtle': '#ECE4D6',
      '--bg-card': '#FBF8F2',
      '--text': '#2B211A',
      '--text-secondary': '#6B5D4F',
      '--text-muted': '#9C8E7E',
      '--border': '#E0D5C5',
      '--border-strong': '#C9BBA7',
      '--accent': '#A8542A',
      '--accent-hover': '#8E4622',
      '--accent-soft': '#F0E0D2',
      '--accent-text': '#FFFFFF',
      '--success': '#3F8F5C',
      '--success-soft': '#E8F5EC',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#B14A3A',
      '--error-soft': '#F8E8E4',
      '--star': '#D9A441',
    },
  ),
  makeTheme(
    'berry',
    'Berry',
    'Soft white + raspberry, playful',
    false,
    {
      '--bg': '#FBF7F8',
      '--bg-subtle': '#F3E9EC',
      '--bg-card': '#FFFFFF',
      '--text': '#231419',
      '--text-secondary': '#6B5560',
      '--text-muted': '#9C8790',
      '--border': '#EBDEE2',
      '--border-strong': '#D6C2C9',
      '--accent': '#C2185B',
      '--accent-hover': '#A0124A',
      '--accent-soft': '#F8E0EA',
      '--accent-text': '#FFFFFF',
      '--success': '#3F8F5C',
      '--success-soft': '#E8F5EC',
      '--warning': '#C9831E',
      '--warning-soft': '#FBF0DC',
      '--error': '#C8453A',
      '--error-soft': '#FBE7E5',
      '--star': '#E8A53A',
    },
  ),
  makeTheme(
    'midnight',
    'Midnight',
    'Charcoal + electric cyan, dark premium',
    true,
    {
      '--bg': '#0E1116',
      '--bg-subtle': '#161A21',
      '--bg-card': '#1A1F28',
      '--text': '#F2F4F8',
      '--text-secondary': '#9CA4B0',
      '--text-muted': '#6B7280',
      '--border': '#262C36',
      '--border-strong': '#363D49',
      '--accent': '#22D3EE',
      '--accent-hover': '#06B6D4',
      '--accent-soft': '#133140',
      '--accent-text': '#06141A',
      '--success': '#34D399',
      '--success-soft': '#0E2E25',
      '--warning': '#FBBF24',
      '--warning-soft': '#332A14',
      '--error': '#F87171',
      '--error-soft': '#3A1A1C',
      '--star': '#FBBF24',
      '--shadow-card': '0 1px 3px rgba(0,0,0,0.3), 0 8px 24px rgba(0,0,0,0.3)',
      '--shadow-hover': '0 4px 12px rgba(0,0,0,0.4), 0 16px 40px rgba(0,0,0,0.5)',
    },
  ),
  makeTheme(
    'aurora',
    'Aurora',
    'Ice white + violet-mint, futuristic 2027',
    false,
    {
      '--bg': '#F5F7FB',
      '--bg-subtle': '#EBEEF6',
      '--bg-card': '#FFFFFF',
      '--text': '#0E1525',
      '--text-secondary': '#4A5B78',
      '--text-muted': '#7E8DA8',
      '--border': '#DDE3F0',
      '--border-strong': '#C4CDE0',
      '--accent': '#6D4EFF',
      '--accent-hover': '#5A3DD6',
      '--accent-soft': '#EDE8FF',
      '--accent-text': '#FFFFFF',
      '--success': '#0EA5A5',
      '--success-soft': '#E0F7F7',
      '--warning': '#E8930C',
      '--warning-soft': '#FBF0DC',
      '--error': '#E0405A',
      '--error-soft': '#FCE8EC',
      '--star': '#FBBF24',
      '--shadow-card': '0 1px 3px rgba(109,78,255,0.04), 0 8px 24px rgba(109,78,255,0.06)',
      '--shadow-hover': '0 4px 12px rgba(109,78,255,0.08), 0 16px 40px rgba(109,78,255,0.10)',
    },
    { '--font-display': "'Inter', system-ui, sans-serif" },
  ),
];

export const defaultTheme: ThemeId = 'ocean';
